language: node_js
node_js:
    - lts/*
before_script:
    - npm install
    - npm install python
    - npm install grunt-cli -g
    - curl -s https://shopify.github.io/themekit/scripts/install.py | sudo python
script:
    - grunt theme-lint
    - npm run js-lint
    - git diff HEAD^ HEAD --name-only >> archivos.txt
    - grunt shell:commit
after_success:
    - grunt createYAMLFileOnEachShop
    - grunt deploy
