language: node_js
node_js:
- lts/*
before_script:
  - npm install
  - npm install python
  - curl -s https://shopify.github.io/themekit/scripts/install.py | sudo python
script: 
  - npm run prettier
  - npm run js-lint
  - grunt theme-lint
after_success:
  # - theme deploy -na
