language: node_js
node_js:
- lts/*
before_script:
  - npm install python
  - npm install @shopify/themekit
script: echo "hola mundo"
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: 
    - bash script/deploy.sh
    on:
      branch: master
