language: node_js
node_js:
- lts/*
before_script:
  - npm install eslint eslint-config-prettier eslint-plugin-jquery prettier eslint-plugin-prettier @shopify/theme-lint --save-dev
  - npm install python
  - curl -s https://shopify.github.io/themekit/scripts/install.py | sudo python
script: 
  - npm run theme-lint
  - npm run js-lint
after_success:
  - theme deploy -na
