language: node_js
node_js:
- lts/*
before_script:
  - npm install -g grunt-cli
  - npm install eslint eslint-config-prettier eslint-plugin-jquery prettier eslint-plugin-prettier @shopify/theme-lint grunt --save-dev
  - npm install python
  - curl -s https://shopify.github.io/themekit/scripts/install.py | sudo python
script: 
  - npm run grunt-default
  - npm run theme-lint #gotta run this inside every shop one by one in travis (by grunt)
  - npm run js-lint
after_success:
  # - theme deploy -na
