language: node_js
node_js:
- lts/*
before_script:
  - npm install python
script: 
- curl -s https://shopify.github.io/themekit/scripts/install.py | sudo python
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: 
    - bash script/deploy.sh
    on:
      branch: master
