massiveshops:
  production:
    password: "pass"
    theme_id: "prod_theme_id"
    store: "https://massiveshops-dev.myshopify.com"
    ignore_files:
      - package-lock.json
      - package.json
      - .prettierignore
      - .gitignore
      - .travis.yml
      - "*.jpg"
      - "*.gif"
      - changed_files.txt
  development:
    password: "pass"
    theme_id: "develop_theme_id"
    store: "https://massiveshops-dev.myshopify.com"
    ignore_files:
      - package-lock.json
      - package.json
      - .prettierignore
      - .gitignore
      - .travis.yml
      - "*.jpg"
      - "*.gif"
      - changed_files.txt