shop1:
  preproduction:
    password: shop1-Theme-pass
    theme_id: 46499561526
    store: can-i-buy-a-feeling.myshopify.com
    proxy: http://localhost:3000
    ignore_files:
      - package-lock.json
      - package.json
      - .prettierignore
      - .gitignore
      - .travis.yml
      - "*.jpg"
      - "*.gif"
  production:
    password: shop1-Theme-pass
    theme_id: 46499528758
    store: can-i-buy-a-feeling.myshopify.com
    proxy: http://localhost:3000
    ignore_files:
      - package-lock.json
      - package.json
      - .prettierignore
      - .gitignore
      - .travis.yml
      - "*.jpg"
      - "*.gif"