shop1:
    develop:
        password: '$clave'
        theme_id: '$theme'
        store: '$tienda'
    production:
        password: '$clave'
        theme_id: '$theme'
        store: '$tienda'
shop2:
    develop:
        password: '$clave'
        theme_id: '$shop2dev'
        store: '$tienda'
    production:
        password: '$clave'
        theme_id: '$shop2preprod'
        store: '$tienda'
