shop1:
    develop:
        password: '$clave'
        theme_id: '$theme'
        store: '$tienda'
    production:
        password: '$clave'
        theme_id: '$theme'
        store: '$tienda'
shop2:
    develop:
        password: 'passwordtienda2'
        theme_id: 'themetienda2'
        store: 'domaintienda2'
    production:
        password: '$passwordtienda2'
        theme_id: '$passwordtienda2'
        store: '$passwordtienda2'
