massiveshops:
  production:
    password: "${massiveshops_pass}"
    theme_id: "${prod_theme_id}"
    store: "${massiveshops_pass}"
    ignore_files:
      - package-lock.json
      - package.json
      - .prettierignore
      - .gitignore
      - .travis.yml
      - "*.jpg"
      - "*.gif"
      - changed_files.txt
  development:
    password: "${massiveshops_pass}"
    theme_id: "${develop_theme_id}"
    store: "${massiveshops_pass}"
    ignore_files:
      - package-lock.json
      - package.json
      - .prettierignore
      - .gitignore
      - .travis.yml
      - "*.jpg"
      - "*.gif"
      - changed_files.txt