development
  password: shop3-devTheme-pass
  theme_id: 123
  store: can-i-buy-a-feeling.myshopify.com
  proxy: http://localhost:3000
  ignore_files: 
    - "*.gif" 
    - "*.jpg" 
    - config/settings_data.json
production
  password: shop3-prodTheme-pass
  theme_id: 456
  store: can-i-buy-a-feeling.myshopify.com
  timeout: 60s
  readonly: true
test
  password: 16ef663594568325d64408ebcdeef528
  theme_id: 789
  store: can-i-buy-a-feeling.myshopify.com
  ignores: ignore.txt
