development
  password: shop1-devTheme-pass
  theme_id: 123
  store: can-i-buy-a-feeling.myshopify.com
  proxy: http://localhost:3000
  ignore_files: 
    - "*.gif" 
    - "*.jpg" 
    - config/settings_data.json
production
  password: shop1-prodTheme-pass
  theme_id: 456
  store: can-i-buy-a-feeling.myshopify.com
  timeout: 60s
  readonly: true
